In [1]:
import pandas as pd
import sqlite3
from datetime import datetime, timedelta

In [2]:
conn = sqlite3.connect("./my_database.db")

In [3]:
addresses = pd.read_sql_query(
    "select * from address", conn,
    parse_dates=['created_at', 'updated_at']
)

In [4]:
contractors = pd.read_sql_query(
    "select * from contractors", conn,
    parse_dates=['created_at', 'updated_at']
)

In [5]:
invoices = pd.read_sql_query(
    "select * from invoice", conn,
    parse_dates=['invoice_date', 'created_at', 'updated_at']
)

In [6]:
line_items = pd.read_sql_query(
    "select * from line_item", conn,
    parse_dates=['created_at', 'updated_at']
)

In [7]:
tickets = pd.read_sql_query(
    "select * from ticket", conn,
    parse_dates=['assigned_at', 'completed_at', 'created_at', 'updated_at', 'start_time', 'due_date']
)

In [8]:
users = pd.read_sql_query(
    "select * from user", conn,
    parse_dates=['created_at', 'updated_at']
)

In [9]:
vendor_users = pd.read_sql_query(
    "select * from vendor_user", conn,
    parse_dates=['created_at', 'updated_at']
)

In [10]:
vendor_wells = pd.read_sql_query(
    "select * from vendor_well", conn,
    parse_dates=['created_at', 'updated_at']
)

In [11]:
vendors = pd.read_sql_query(
    "select * from vendor", conn,
    parse_dates=['created_at', 'updated_at']
)

In [12]:
well_locations = pd.read_sql_query(
    "select * from well_location", conn,
    parse_dates=['created_at', 'updated_at']
)

In [13]:
wells = pd.read_sql_query(
    "select * from well", conn,
    parse_dates=['created_at', 'updated_at']
)

In [14]:
work_orders = pd.read_sql_query(
    "select * from work_orders", conn,
    parse_dates=['created_at', 'updated_at']
)

In [15]:
contractor_performance = pd.read_sql_query(
    "select * from contractor_performance", conn,
    parse_dates=['created_at', 'updated_at']
)

In [16]:
# vendor_tickets = pd.merge(vendors, tickets, on='vendor_id', suffixes=['_vendor', '_ticket'])

In [17]:
# vendor_tickets.head()

In [18]:
tickets.head()

,ticket_id,work_order_id,description,assigned_contractor,priority,status,vendor_id,start_time,due_date,assigned_at,...,estimated_quantity,unit,special_requirements,anomaly_flag,anomaly_reason,created_at,updated_at,created_by,updated_by,additional_information
0,865bbf21-a309-48f2-8ace-9aa0f8f74845,771d5a8d-8dca-4d65-9c50-7bc24fc89fdf,Should me generation. Help accept build style ...,c23be650-8393-4832-9017-b4bdfa3fd6aa,routine,assigned,bb677a64-0cf1-42f0-8662-c1ad2443a1e0,2026-03-01 05:46:00,2026-04-05 18:31:53,2026-02-26 15:01:07,...,63,hours,Theory Congress day debate marriage this home.,0,Bit sell reach.,2026-02-20 15:15:13,2026-04-07 10:43:08.119194,52c14610-7454-4f77-8742-5c2bda6b2fb8,a5110c40-9151-4d9e-ac43-94965c2590ea,"[{""name"": ""Lisa Chang"", ""residency"": ""4960 Sco..."
1,7a115c37-14a0-4255-8dd5-f819cbac28d7,0b4e9602-b8c3-4780-9def-d09ecdfcdfef,Total chair player.\nFour cold mission we enou...,d905186e-b395-4904-8632-cd2b42c0ac9e,routine,assigned,4851c453-cc2f-41cf-a138-eb4d49b84547,2024-08-16 07:30:32,2024-08-22 19:45:28,2024-08-10 12:12:04,...,53,hours,Past successful age attention company next pop...,0,Painting pattern he suffer tell.,2024-08-10 07:32:31,2026-04-07 10:43:08.121614,e121fbf2-f03f-4b3a-b3b1-d039ccf25b10,d9fd8aa9-3d45-4611-b149-cb25432965b0,"[{""name"": ""Michael Anderson"", ""residency"": ""07..."
2,8d40ed8e-9f74-4296-9a20-c4385177c72c,c6116942-f9a0-4724-bde0-a4e3ca697646,Life our that. Really stock address it busines...,61704b62-3d6a-47c1-bb0c-ea9880452eaa,urgent,completed,f6169088-cc06-4c9c-ac65-81bf7614989b,2025-07-16 02:41:18,2025-08-08 07:48:51,2025-07-14 09:41:47,...,85,hours,Huge catch dinner nice.,1,NaN,2025-07-05 21:50:01,2026-04-07 10:43:08.123847,2a9d300f-d40a-4a1e-84f2-b6b3f7168cc4,8cb23664-7c61-41d6-907f-70f56aad7819,"[{""name"": ""Robert Curtis Jr."", ""residency"": ""1..."
3,08ff97f1-77c1-44b9-941a-33196cd57773,84ac5558-aa83-4ed3-9c60-c60cedc09eb8,Fact participant individual miss. Size respons...,013cdc88-a774-494d-9eb5-498d12708fc8,routine,assigned,739ed2bf-6237-4665-b46f-ef4f80e0679b,2025-02-19 11:27:53,2025-03-20 05:47:22,2025-02-18 13:22:18,...,53,hours,Standard everyone simple girl sure management.,1,Statement hope yes loss realize.,2025-02-09 09:44:51,2026-04-07 10:43:08.125915,a1ed513b-6728-49e0-863d-f361f27db48b,e8e01ffc-4a8d-4051-ac48-2c23dbd6edc5,"[{""name"": ""Jacqueline Perez"", ""residency"": ""31..."
4,867e020f-cebd-4aca-9ca2-c7fece713766,ad0a78a4-82b7-431e-b187-23903b3cda5b,Animal effort foot course smile plant election...,706d7b63-ec3c-4471-96f1-e42e1f39d0b4,routine,assigned,99d37a94-dff8-4a1a-9144-2ed3c16fd181,2025-06-30 04:32:37,2025-08-02 10:28:19,2025-06-23 18:55:40,...,29,hours,True theory provide attorney support week each.,0,NaN,2025-06-22 02:51:31,2026-04-07 10:43:08.128125,5346ad65-25ef-4cb9-b77a-1a91a017cbd6,d2c3435a-62a0-4991-b74b-0750167a5e9d,"[{""name"": ""Heather Walker"", ""residency"": ""5102..."

In [19]:
# tickets['quarter'] = tickets['created_at'].dt.quarter

In [20]:
# completed_tickets = tickets[tickets['status'] == 'completed']
# completed_tickets.shape

In [21]:
# completed_tickets['completion_time'] = completed_tickets['completed_at'] - completed_tickets['assigned_at']

In [22]:
# completed_tickets['response_time'] = completed_tickets['start_time'] - completed_tickets['assigned_at']

In [23]:
# completed_tickets.groupby('quarter')['completion_time'].mean()

In [24]:
# completed_tickets.groupby('quarter')['response_time'].mean()

In [25]:
# completed_tickets.groupby('quarter')['ticket_id'].count()

In [26]:
# tickets['month'] = tickets['created_at'].dt.month_name()

In [27]:
# tickets[tickets['quarter'] == 4].month.value_counts()

In [28]:
# completed_tickets.groupby('vendor_id')['completion_time'].mean().sort_values(ascending=False)

In [29]:
# completed_tickets.groupby('vendor_id')['response_time'].mean().sort_values(ascending=False)

In [30]:
# completed_tickets.groupby('vendor_id')['ticket_id'].count()

In [31]:
# vendor_kpis = completed_tickets.groupby('vendor_id').agg({
#     "completion_time": 'mean',
#     "response_time": 'mean',
#     "ticket_id": 'count'
# })
# vendor_kpis

In [32]:
# vendor_info = vendors[['vendor_id', 'company_name']]

In [33]:
# vendor_info

In [34]:
# pd.merge(vendor_info, vendor_kpis, on='vendor_id')

# Vendor/Client Admin KPIs

## On Time Delivery %
percentage of tickets completed on time within a specified range

In [35]:
cols = ['ticket_id', 'created_at', 'assigned_at', 'start_time', 'completed_at', 'due_date']

In [36]:
def overall_vendor_on_time_delivery(start_time, end_time=datetime.now()):
    start_time = pd.to_datetime(start_time)
    end_time = pd.to_datetime(end_time)
    df = tickets[tickets['created_at'].between(start_time, end_time)]
    completed_late = df['completed_at'] > df['due_date']
    overdue = (df['completed_at'].isna()) & (df['due_date'] < end_time)

    df['on_time'] = ~(completed_late | overdue)

    ticket_kpi = df.groupby('vendor_id').agg({
        'on_time': 'mean',
        'ticket_id': 'count'
    })
    ticket_kpi['on_time'] = (ticket_kpi['on_time'] * 100).round(2)
    vendor_info = vendors[['vendor_id', 'company_name']]

    vendor_kpi = pd.merge(vendor_info, ticket_kpi, on='vendor_id').sort_values(by='on_time', ascending=False)
    return vendor_kpi

In [37]:
def overall_vendor_on_time_delivery_2(start_time, end_time=datetime.now()):
    query = """
        select 
            v.company_name,
            round(avg(
                case 
                    when (t.completed_at > t.due_date) 
                         or (t.completed_at is null and t.due_date < ?)
                    then 0
                    else 1
                end
            ) * 100, 2) as on_time,
            count(t.ticket_id) as ticket_count
        from ticket t
        join vendor v using (vendor_id)
        where t.created_at between ? and ?
        group by v.vendor_id, v.company_name
        order by on_time desc;
    """

    vendor_kpi = pd.read_sql(
        query,
        conn,
        params=(end_time, start_time, end_time)
    )

    return vendor_kpi

In [38]:
# three_months = pd.Timestamp.now() - pd.DateOffset(months=3)
# tickets_created_3_months = tickets[tickets['created_at'] >= three_months].reset_index()

# completed_late = tickets_created_3_months['completed_at'] > tickets_created_3_months['due_date']
# overdue = (tickets_created_3_months['completed_at'].isna()) & (tickets_created_3_months['due_date'] < pd.Timestamp.now())

# tickets_created_3_months['on_time'] = ~(completed_late | overdue)

# # tickets_created_3_months[cols].head(10)

# tickets_created_3_months['on_time'].value_counts(normalize=True)

# # tickets_created_3_months[tickets_created_3_months['on_time'] == True][cols]

# tickets_created_3_months.groupby('vendor_id')['on_time'].mean().round(4) * 100

In [39]:
nov_2025 = datetime.strptime('2025-11-01', '%Y-%m-%d').date()
feb_2026 = datetime.strptime('2026-03-01', '%Y-%m-%d').date()

In [40]:
overall_vendor_on_time_delivery(nov_2025, feb_2026)

,vendor_id,company_name,on_time,ticket_id
9,bb677a64-0cf1-42f0-8662-c1ad2443a1e0,"Baldwin, Cohen and Stephenson",43.06,72
2,4851c453-cc2f-41cf-a138-eb4d49b84547,Brown and Sons,37.50,96
5,2155d1b8-bf6c-417b-88cf-531610c1bc0b,Jefferson-Valencia,32.89,76
6,bea4014f-48bc-4afa-a892-b3c0adb2aa33,Harper-Vincent,27.12,59
3,0b4da9c3-c7eb-4440-9931-31f1d9165817,Howard-James,27.08,48
4,f6169088-cc06-4c9c-ac65-81bf7614989b,"Moreno, Rosario and Johns",23.64,55
8,739ed2bf-6237-4665-b46f-ef4f80e0679b,Cunningham and Sons,21.15,52
0,99d37a94-dff8-4a1a-9144-2ed3c16fd181,"Baker, Johnson and Palmer",20.00,135
1,b1af2404-1078-47e7-af2e-a4e2be043b5e,Stone Ltd,17.74,62
7,272a82ce-913a-48df-b4ec-2c85f20a0994,Smith-Ballard,4.62,65

In [41]:
overall_vendor_on_time_delivery_2(nov_2025, feb_2026)

                    company_name  on_time  ticket_count
0  Baldwin, Cohen and Stephenson    43.06            72
1                 Brown and Sons    37.50            96
2             Jefferson-Valencia    32.89            76
3                 Harper-Vincent    27.12            59
4                   Howard-James    27.08            48
5      Moreno, Rosario and Johns    23.64            55
6            Cunningham and Sons    21.15            52
7      Baker, Johnson and Palmer    20.00           135
8                      Stone Ltd    17.74            62
9                  Smith-Ballard     4.62            65

In [42]:
overall_vendor_on_time_delivery(nov_2025)

,vendor_id,company_name,on_time,ticket_id
9,bb677a64-0cf1-42f0-8662-c1ad2443a1e0,"Baldwin, Cohen and Stephenson",23.61,72
6,bea4014f-48bc-4afa-a892-b3c0adb2aa33,Harper-Vincent,20.34,59
7,272a82ce-913a-48df-b4ec-2c85f20a0994,Smith-Ballard,14.10,78
8,739ed2bf-6237-4665-b46f-ef4f80e0679b,Cunningham and Sons,13.46,52
2,4851c453-cc2f-41cf-a138-eb4d49b84547,Brown and Sons,12.87,101
5,2155d1b8-bf6c-417b-88cf-531610c1bc0b,Jefferson-Valencia,11.84,76
4,f6169088-cc06-4c9c-ac65-81bf7614989b,"Moreno, Rosario and Johns",9.52,63
3,0b4da9c3-c7eb-4440-9931-31f1d9165817,Howard-James,8.93,56
0,99d37a94-dff8-4a1a-9144-2ed3c16fd181,"Baker, Johnson and Palmer",6.62,136
1,b1af2404-1078-47e7-af2e-a4e2be043b5e,Stone Ltd,6.06,66

In [43]:
%timeit overall_vendor_on_time_delivery(nov_2025, feb_2026)

4.55 ms ± 1.29 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [44]:
%timeit overall_vendor_on_time_delivery_2(nov_2025, feb_2026)

14.3 ms ± 4.27 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [45]:
(tickets['completed_at'].dt.normalize() == datetime.today().date()).sum()

np.int64(0)

In [46]:
tickets['completed_at'].dt.normalize().value_counts()

completed_at
2025-08-09    6
2025-08-05    6
2025-10-14    6
2025-04-10    6
2025-04-06    6
             ..
2025-04-08    1
2025-05-19    1
2026-01-13    1
2026-01-26    1
2024-12-04    1
Name: count, Length: 565, dtype: int64

## Average Duration of Ticket

In [47]:
df = tickets[~tickets['completed_at'].isna()]
df.shape

(1144, 25)

In [48]:
df['completion_time'] = df['completed_at'] - df['assigned_at']

In [52]:
df['completion_time'].mean()

Timedelta('18 days 22:39:20.180944')

In [53]:
def overall_vendor_ticket_duration(start_time, end_time=datetime.now()):
    start_time = pd.to_datetime(start_time)
    end_time = pd.to_datetime(end_time)
    df = tickets[tickets['completed_at'].between(start_time, end_time)] # all completed tickets in time range
    df['completion_time'] = df['completed_at'] - df['assigned_at']

    kpi = df.groupby('vendor_id')['completion_time'].mean().sort_values(ascending=True)
    vendor_info = vendors[['vendor_id', 'company_name']]

    vendor_kpi = pd.merge(vendor_info, kpi, on='vendor_id')

    return vendor_kpi

In [54]:
overall_vendor_ticket_duration(nov_2025, feb_2026)

,vendor_id,company_name,completion_time
0,99d37a94-dff8-4a1a-9144-2ed3c16fd181,"Baker, Johnson and Palmer",19 days 10:04:45.200000
1,4851c453-cc2f-41cf-a138-eb4d49b84547,Brown and Sons,14 days 15:14:34.750000
2,0b4da9c3-c7eb-4440-9931-31f1d9165817,Howard-James,22 days 12:12:54.428571
3,f6169088-cc06-4c9c-ac65-81bf7614989b,"Moreno, Rosario and Johns",18 days 16:00:56.750000
4,2155d1b8-bf6c-417b-88cf-531610c1bc0b,Jefferson-Valencia,22 days 22:48:57.526315
5,bea4014f-48bc-4afa-a892-b3c0adb2aa33,Harper-Vincent,14 days 22:22:37.352941
6,272a82ce-913a-48df-b4ec-2c85f20a0994,Smith-Ballard,13 days 12:37:30.777777
7,739ed2bf-6237-4665-b46f-ef4f80e0679b,Cunningham and Sons,16 days 01:21:35.375000
8,bb677a64-0cf1-42f0-8662-c1ad2443a1e0,"Baldwin, Cohen and Stephenson",15 days 08:42:20

In [55]:
overall_vendor_ticket_duration(nov_2025)

,vendor_id,company_name,completion_time
0,99d37a94-dff8-4a1a-9144-2ed3c16fd181,"Baker, Johnson and Palmer",19 days 10:04:45.200000
1,4851c453-cc2f-41cf-a138-eb4d49b84547,Brown and Sons,14 days 22:31:23.444444
2,0b4da9c3-c7eb-4440-9931-31f1d9165817,Howard-James,23 days 10:33:20.187500
3,f6169088-cc06-4c9c-ac65-81bf7614989b,"Moreno, Rosario and Johns",24 days 11:24:14.875000
4,2155d1b8-bf6c-417b-88cf-531610c1bc0b,Jefferson-Valencia,23 days 16:03:58.608695
5,bea4014f-48bc-4afa-a892-b3c0adb2aa33,Harper-Vincent,14 days 22:22:37.352941
6,272a82ce-913a-48df-b4ec-2c85f20a0994,Smith-Ballard,17 days 02:39:16.083333
7,739ed2bf-6237-4665-b46f-ef4f80e0679b,Cunningham and Sons,19 days 22:13:09.062500
8,bb677a64-0cf1-42f0-8662-c1ad2443a1e0,"Baldwin, Cohen and Stephenson",15 days 08:42:20

## Currently Open Tickets

In [56]:
def overall_vendor_open_tickets():
    open_tickets = tickets[tickets['status'] != 'completed']
    kpi = pd.pivot_table(open_tickets, index='vendor_id', columns='status', values='ticket_id', aggfunc='count').reset_index()
    kpi['total'] = kpi['assigned'] + kpi['in progress']
    vendor_info = vendors[['vendor_id', 'company_name']]

    vendor_kpi = pd.merge(vendor_info, kpi, on='vendor_id')
    return vendor_kpi

In [57]:
overall_vendor_open_tickets()

,vendor_id,company_name,assigned,in progress,total
0,99d37a94-dff8-4a1a-9144-2ed3c16fd181,"Baker, Johnson and Palmer",469,96,565
1,b1af2404-1078-47e7-af2e-a4e2be043b5e,Stone Ltd,332,50,382
2,4851c453-cc2f-41cf-a138-eb4d49b84547,Brown and Sons,548,76,624
3,0b4da9c3-c7eb-4440-9931-31f1d9165817,Howard-James,284,45,329
4,f6169088-cc06-4c9c-ac65-81bf7614989b,"Moreno, Rosario and Johns",372,73,445
5,2155d1b8-bf6c-417b-88cf-531610c1bc0b,Jefferson-Valencia,294,32,326
6,bea4014f-48bc-4afa-a892-b3c0adb2aa33,Harper-Vincent,236,50,286
7,272a82ce-913a-48df-b4ec-2c85f20a0994,Smith-Ballard,278,63,341
8,739ed2bf-6237-4665-b46f-ef4f80e0679b,Cunningham and Sons,258,28,286
9,bb677a64-0cf1-42f0-8662-c1ad2443a1e0,"Baldwin, Cohen and Stephenson",235,37,272

## Average Rating Per Vendor

In [58]:
def overall_vendor_performance():
    vendor_contractor = pd.merge(vendors, contractors, on='vendor_id')
    vc_performance = pd.merge(vendor_contractor, contractor_performance, on='contractor_id')
    return vc_performance.groupby('company_name')['rating'].mean().round(2).sort_values(ascending=False)

In [59]:
overall_vendor_performance()

company_name
Baker, Johnson and Palmer        3.17
Howard-James                     3.14
Harper-Vincent                   3.11
Stone Ltd                        3.03
Baldwin, Cohen and Stephenson    3.00
Jefferson-Valencia               2.97
Moreno, Rosario and Johns        2.95
Brown and Sons                   2.93
Cunningham and Sons              2.91
Smith-Ballard                    2.89
Name: rating, dtype: float64

In [66]:
def overall_vendor_performance_2():
    vendor_contractor_performance = pd.read_sql_query(
        """
        select v.company_name, round(cp.avg_rating, 2) as rating
        from (
            select c.vendor_id, avg(cp.rating) as avg_rating
            from contractor_performance cp
            join contractors c using (contractor_id)
            group by c.vendor_id
        ) cp
        join vendor v using (vendor_id)
        order by cp.avg_rating desc;
        """, conn
    )
    # print(vendor_contractor_performance.head())
    return vendor_contractor_performance # vendor_contractor_performance.groupby('company_name')['rating'].mean().round(2).sort_values(ascending=False)

In [67]:
overall_vendor_performance_2()

                    company_name  rating
0      Baker, Johnson and Palmer    3.17
1                   Howard-James    3.14
2                 Harper-Vincent    3.11
3                      Stone Ltd    3.03
4  Baldwin, Cohen and Stephenson    3.00
5             Jefferson-Valencia    2.97
6      Moreno, Rosario and Johns    2.95
7                 Brown and Sons    2.93
8            Cunningham and Sons    2.91
9                  Smith-Ballard    2.89

In [68]:
%timeit overall_vendor_performance()

4.76 ms ± 586 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [69]:
%timeit overall_vendor_performance_2()

955 μs ± 49.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)