In [38]:
import pandas as pd
import sqlite3
from datetime import datetime, timedelta

In [2]:
conn = sqlite3.connect("./my_database.db")

addresses = pd.read_sql_query(
    "select * from address", conn,
    parse_dates=['created_at', 'updated_at']
)

contractors = pd.read_sql_query(
    "select * from contractors", conn,
    parse_dates=['created_at', 'updated_at']
)

invoices = pd.read_sql_query(
    "select * from invoice", conn,
    parse_dates=['invoice_date', 'created_at', 'updated_at']
)

line_items = pd.read_sql_query(
    "select * from line_item", conn,
    parse_dates=['created_at', 'updated_at']
)

tickets = pd.read_sql_query(
    "select * from ticket", conn,
    parse_dates=['assigned_at', 'completed_at', 'created_at', 'updated_at', 'start_time', 'due_date']
)

users = pd.read_sql_query(
    "select * from user", conn,
    parse_dates=['created_at', 'updated_at']
)

vendor_users = pd.read_sql_query(
    "select * from vendor_user", conn,
    parse_dates=['created_at', 'updated_at']
)

vendor_wells = pd.read_sql_query(
    "select * from vendor_well", conn,
    parse_dates=['created_at', 'updated_at']
)

vendors = pd.read_sql_query(
    "select * from vendor", conn,
    parse_dates=['created_at', 'updated_at']
)

well_locations = pd.read_sql_query(
    "select * from well_location", conn,
    parse_dates=['created_at', 'updated_at']
)

wells = pd.read_sql_query(
    "select * from well", conn,
    parse_dates=['created_at', 'updated_at']
)

work_orders = pd.read_sql_query(
    "select * from work_orders", conn,
    parse_dates=['created_at', 'updated_at']
)

In [3]:
# vendor_tickets = pd.merge(vendors, tickets, on='vendor_id', suffixes=['_vendor', '_ticket'])

In [4]:
# vendor_tickets.head()

In [5]:
tickets.head()

,ticket_id,work_order_id,description,assigned_contractor,priority,status,vendor_id,start_time,due_date,assigned_at,...,estimated_quantity,unit,special_requirements,anomaly_flag,anomaly_reason,created_at,updated_at,created_by,updated_by,additional_information
0,c4773af3-3c64-4268-9e17-d46b49b42700,0d4fbd07-ed2b-45f0-922d-b2cd162ef3ce,Meet create return about stock church. Later w...,cafaf1bb-76f4-483e-8e96-711adbeb0bc2,routine,assigned,4e71ccf3-f7e5-47cb-a374-de231743e510,2025-06-16 19:33:02,2025-06-19 08:07:06,2025-06-16 00:52:54,...,77,hours,Wall project above own continue term specific.,1,NaN,2025-06-15 11:13:01,2026-04-04 16:05:44.011060,efddadf5-176d-4639-b976-6dda152979da,5e195a15-5fff-4763-aa0e-40de30803a33,"[{""name"": ""Wesley Williams"", ""residency"": ""PSC..."
1,8d0ae64b-d737-4d8e-b97a-7bfaaa5c1f5b,3277dd05-4e10-4b3d-9a69-55e28f0eebf6,Democrat hair respond few argue. Any manage re...,c6415713-5406-49b7-b56d-c0b6606f9087,emergency,in progress,c6e89bc6-3d6c-4ecc-ac42-880ac49a39f3,2025-08-17 07:15:39,2025-08-22 11:09:31,2025-08-15 20:13:42,...,55,hours,Ahead positive make hotel strategy president.,1,Agree idea conference push each office.,2025-08-15 09:02:37,2026-04-04 16:05:44.013191,5d418b81-a895-43b4-895e-ae07c68a4562,3b730578-bcc1-4159-a62b-9224a984fd41,"[{""name"": ""Mrs. Angela Butler"", ""residency"": ""..."
2,f159e918-29a5-408e-8438-c8c5fc2c4922,5f028d73-ad0f-4b13-a46b-74f454ef53e4,Hot none already result major star be. Lot let...,f6fc10a6-0f63-4862-8345-d639c76c41ae,urgent,assigned,be2d0469-82fe-49ac-a723-44696e569a77,2026-01-19 21:52:32,2026-01-21 10:27:52,2026-01-18 13:39:40,...,33,hours,When hand seek you if above night.,0,Chance its size.,2026-01-18 08:01:49,2026-04-04 16:05:44.015338,6adefa93-af5f-435f-9373-153b474a47b7,dbb063f0-e7cb-40ac-9a79-2d985125a3c8,"[{""name"": ""Jesus Salazar"", ""residency"": ""89039..."
3,d2a03c46-eb9f-4d0e-9a16-ebdc1d6df7f0,2ea48510-e89c-4a15-99fe-8ebd454c50f6,Hard nature alone family might thought. Countr...,9e0ac2a1-bc4a-4c76-ae0b-d1a567b7b8cd,routine,assigned,0d3f3cfe-3a2f-4929-b3b4-1bf15e8044fa,2025-05-04 09:19:15,2025-05-08 18:24:56,2025-05-01 22:07:06,...,72,hours,Already factor theory really any.,0,Player account receive behind.,2025-05-01 13:14:32,2026-04-04 16:05:44.017498,f08dc594-7d07-47fb-8982-f28b8451e09d,0fe13e91-f344-4f75-a1b6-7ab1e022fcc4,"[{""name"": ""Melissa Hood"", ""residency"": ""0429 A..."
4,db2eab3c-b0d0-4093-b804-6e36825301a2,9ba24f02-a96e-4138-aec8-e37a18a4e589,Green image attorney interest natural.\nClear ...,d1d30e15-ae76-4768-b301-923ffc321503,urgent,completed,f2ca34ca-4441-4bb5-86ad-871b9ad51ef3,2025-12-21 05:08:52,2025-12-29 06:42:58,2025-12-20 13:17:12,...,44,hours,Design police have fly job occur.,0,NaN,2025-12-20 12:36:32,2026-04-04 16:05:44.019645,c93bd6a3-fecb-443a-8194-0593acc31654,8e461c35-3b3b-45f5-a33e-c5d63c00d416,"[{""name"": ""Clifford Brown"", ""residency"": ""7428..."

In [6]:
# tickets['quarter'] = tickets['created_at'].dt.quarter

In [7]:
# completed_tickets = tickets[tickets['status'] == 'completed']
# completed_tickets.shape

In [8]:
# completed_tickets['completion_time'] = completed_tickets['completed_at'] - completed_tickets['assigned_at']

In [9]:
# completed_tickets['response_time'] = completed_tickets['start_time'] - completed_tickets['assigned_at']

In [10]:
# completed_tickets.groupby('quarter')['completion_time'].mean()

In [11]:
# completed_tickets.groupby('quarter')['response_time'].mean()

In [12]:
# completed_tickets.groupby('quarter')['ticket_id'].count()

In [13]:
# tickets['month'] = tickets['created_at'].dt.month_name()

In [14]:
# tickets[tickets['quarter'] == 4].month.value_counts()

In [15]:
# completed_tickets.groupby('vendor_id')['completion_time'].mean().sort_values(ascending=False)

In [16]:
# completed_tickets.groupby('vendor_id')['response_time'].mean().sort_values(ascending=False)

In [17]:
# completed_tickets.groupby('vendor_id')['ticket_id'].count()

In [18]:
# vendor_kpis = completed_tickets.groupby('vendor_id').agg({
#     "completion_time": 'mean',
#     "response_time": 'mean',
#     "ticket_id": 'count'
# })
# vendor_kpis

In [19]:
# vendor_info = vendors[['vendor_id', 'company_name']]

In [20]:
# vendor_info

In [21]:
# pd.merge(vendor_info, vendor_kpis, on='vendor_id')

# Vendor/Client Admin KPIs

## On Time Delivery %
percentage of tickets completed on time within a specified range

In [22]:
cols = ['ticket_id', 'created_at', 'assigned_at', 'start_time', 'completed_at', 'due_date']

In [45]:
def vendor_on_time_delivery(start_time, end_time=datetime.now()):
    df = tickets[tickets['created_at'].between(start_time, end_time)]
    completed_late = df['completed_at'] > df['due_date']
    overdue = (df['completed_at'].isna()) & (df['due_date'] < end_time)

    df['on_time'] = ~(completed_late | overdue)

    ticket_kpi = df.groupby('vendor_id')['on_time'].mean().round(4) * 100
    vendor_info = vendors[['vendor_id', 'company_name']]

    vendor_kpi = pd.merge(vendor_info, ticket_kpi, on='vendor_id')
    return vendor_kpi

In [23]:
three_months = pd.Timestamp.now() - pd.DateOffset(months=3)
tickets_created_3_months = tickets[tickets['created_at'] >= three_months].reset_index()

In [24]:
completed_late = tickets_created_3_months['completed_at'] > tickets_created_3_months['due_date']
overdue = (tickets_created_3_months['completed_at'].isna()) & (tickets_created_3_months['due_date'] < pd.Timestamp.now())

tickets_created_3_months['on_time'] = ~(completed_late | overdue)

In [25]:
# tickets_created_3_months[cols].head(10)

In [26]:
tickets_created_3_months['on_time'].value_counts(normalize=True)

on_time
False    0.771552
True     0.228448
Name: proportion, dtype: float64

In [27]:
# tickets_created_3_months[tickets_created_3_months['on_time'] == True][cols]

In [32]:
tickets_created_3_months.groupby('vendor_id')['on_time'].mean().round(4) * 100

vendor_id
0d3f3cfe-3a2f-4929-b3b4-1bf15e8044fa    24.00
129c21f4-f606-4ff9-8c3c-ab6cd99c9bec    24.00
4c069cfd-54b8-4771-adf8-8f7861413223    20.83
4e71ccf3-f7e5-47cb-a374-de231743e510    18.18
883e20bc-9243-4f29-ac9b-5748d506b004    18.18
be2d0469-82fe-49ac-a723-44696e569a77     7.41
c6e89bc6-3d6c-4ecc-ac42-880ac49a39f3    25.00
cbd82bc3-3a31-4e01-a6b8-878adf10047b    22.73
d38fae09-fcc3-448c-8a39-953dec63d2f0    37.50
f2ca34ca-4441-4bb5-86ad-871b9ad51ef3    38.89
Name: on_time, dtype: float64

In [33]:
import datetime

In [37]:
datetime.datetime.strptime('2026-04-10', '%Y-%m-%d')

datetime.datetime(2026, 4, 10, 0, 0)

In [42]:
nov_2025 = datetime.strptime('2025-11-01', '%Y-%m-%d')
feb_2026 = datetime.strptime('2026-03-01', '%Y-%m-%d')

In [46]:
vendor_on_time_delivery(nov_2025, feb_2026)

                              vendor_id                 company_name  on_time
0  c6e89bc6-3d6c-4ecc-ac42-880ac49a39f3                 Anderson PLC    26.47
1  4c069cfd-54b8-4771-adf8-8f7861413223               Patel and Sons    10.53
2  cbd82bc3-3a31-4e01-a6b8-878adf10047b  Rogers, Henderson and Weiss    32.14
3  d38fae09-fcc3-448c-8a39-953dec63d2f0                 Lewis-Jordan    28.21
4  be2d0469-82fe-49ac-a723-44696e569a77   Gonzalez, Abbott and Jones    17.95
5  f2ca34ca-4441-4bb5-86ad-871b9ad51ef3                  Bailey-Hart    45.00
6  129c21f4-f606-4ff9-8c3c-ab6cd99c9bec                 Spencer-Case    23.81
7  883e20bc-9243-4f29-ac9b-5748d506b004                     Long Inc    20.00
8  4e71ccf3-f7e5-47cb-a374-de231743e510   Hicks, Bonilla and Douglas    23.68
9  0d3f3cfe-3a2f-4929-b3b4-1bf15e8044fa      Perez, Stein and Waters    29.03

In [47]:
vendor_on_time_delivery(nov_2025)

                              vendor_id                 company_name  on_time
0  c6e89bc6-3d6c-4ecc-ac42-880ac49a39f3                 Anderson PLC    23.68
1  4c069cfd-54b8-4771-adf8-8f7861413223               Patel and Sons    16.33
2  cbd82bc3-3a31-4e01-a6b8-878adf10047b  Rogers, Henderson and Weiss    27.78
3  d38fae09-fcc3-448c-8a39-953dec63d2f0                 Lewis-Jordan    29.17
4  be2d0469-82fe-49ac-a723-44696e569a77   Gonzalez, Abbott and Jones    14.89
5  f2ca34ca-4441-4bb5-86ad-871b9ad51ef3                  Bailey-Hart    43.75
6  129c21f4-f606-4ff9-8c3c-ab6cd99c9bec                 Spencer-Case    25.00
7  883e20bc-9243-4f29-ac9b-5748d506b004                     Long Inc    18.18
8  4e71ccf3-f7e5-47cb-a374-de231743e510   Hicks, Bonilla and Douglas    20.97
9  0d3f3cfe-3a2f-4929-b3b4-1bf15e8044fa      Perez, Stein and Waters    28.21