In [1]:
import pandas as pd
import sqlite3
from datetime import datetime, timedelta

In [2]:
conn = sqlite3.connect("./my_database.db")

addresses = pd.read_sql_query(
    "select * from address", conn,
    parse_dates=['created_at', 'updated_at']
)

contractors = pd.read_sql_query(
    "select * from contractors", conn,
    parse_dates=['created_at', 'updated_at']
)

invoices = pd.read_sql_query(
    "select * from invoice", conn,
    parse_dates=['invoice_date', 'created_at', 'updated_at']
)

line_items = pd.read_sql_query(
    "select * from line_item", conn,
    parse_dates=['created_at', 'updated_at']
)

tickets = pd.read_sql_query(
    "select * from ticket", conn,
    parse_dates=['assigned_at', 'completed_at', 'created_at', 'updated_at', 'start_time', 'due_date']
)

users = pd.read_sql_query(
    "select * from user", conn,
    parse_dates=['created_at', 'updated_at']
)

vendor_users = pd.read_sql_query(
    "select * from vendor_user", conn,
    parse_dates=['created_at', 'updated_at']
)

vendor_wells = pd.read_sql_query(
    "select * from vendor_well", conn,
    parse_dates=['created_at', 'updated_at']
)

vendors = pd.read_sql_query(
    "select * from vendor", conn,
    parse_dates=['created_at', 'updated_at']
)

well_locations = pd.read_sql_query(
    "select * from well_location", conn,
    parse_dates=['created_at', 'updated_at']
)

wells = pd.read_sql_query(
    "select * from well", conn,
    parse_dates=['created_at', 'updated_at']
)

work_orders = pd.read_sql_query(
    "select * from work_orders", conn,
    parse_dates=['created_at', 'updated_at']
)

In [3]:
# vendor_tickets = pd.merge(vendors, tickets, on='vendor_id', suffixes=['_vendor', '_ticket'])

In [4]:
# vendor_tickets.head()

In [5]:
tickets.head()

,ticket_id,work_order_id,description,assigned_contractor,priority,status,vendor_id,start_time,due_date,assigned_at,...,estimated_quantity,unit,special_requirements,anomaly_flag,anomaly_reason,created_at,updated_at,created_by,updated_by,additional_information
0,7ba98e7d-6aa2-4e4e-a102-6c81937a6355,497cba07-21a1-4dce-9b3a-b5f577069709,Know politics notice bad on surface informatio...,76cf30a3-a347-47af-a76d-8f68db51f2b7,routine,assigned,0ded7f06-ed67-4a95-a21d-2c431e38c883,2025-11-26 23:55:11,2025-12-08 17:23:22,2025-11-25 04:15:09,...,18,hours,Arm table human three.,1,Wrong challenge ask find happy economy analysis.,2025-11-25 01:52:17,2026-04-05 08:43:54.354827,94a59949-03b9-4eae-b4ab-38c09c66873a,98c310fd-0ed2-44ad-aad9-9f3750017926,"[{""name"": ""Douglas Lewis"", ""residency"": ""1049 ..."
1,c4321d99-1a32-4808-91e5-211908e2237a,db949b4c-9bec-44b4-ac65-0d849ae3f080,Possible clear election run clearly. Car camer...,49840b14-1b96-4402-b96a-95c5403e25b3,routine,in progress,084e231e-e1f9-43f1-9eea-8501ecc87efe,2025-12-14 15:45:02,2025-12-22 10:46:32,2025-12-11 18:11:12,...,55,hours,Book hope only population lot center thing.,0,NaN,2025-12-10 17:26:26,2026-04-05 08:43:54.358388,3601e06d-37ea-4551-b849-ee07e75ed608,60ca669e-1c06-47ef-974d-2137f3ca9679,"[{""name"": ""Robert Bell"", ""residency"": ""984 Gai..."
2,4c05b79e-21d3-4f9b-babf-55e3e1ccd1ae,a6f696e3-c64b-489e-a1cc-20ce1fc08d5d,Write star around agent water. Career seat lea...,0386de5f-ae4a-4c35-8c89-b4cb29336db1,urgent,completed,8d975f8a-3c15-42d6-a033-74e9628c5264,2025-04-17 17:11:03,2025-04-22 07:03:44,2025-04-15 11:54:13,...,56,hours,Born person yet side claim.,0,NaN,2025-04-15 02:39:17,2026-04-05 08:43:54.361726,f02c3a45-a378-4783-9015-04ee129dce2b,5a57013a-16d4-4b40-b786-794ba94960ce,"[{""name"": ""Eric Davis"", ""residency"": ""1548 Pau..."
3,d5d3099d-99c9-4f3d-ba4d-9c8efe77a5cd,ade5891e-aceb-45d5-8a9b-e988679461c0,Line good study become. Wrong eye reveal recen...,8df86cac-2fd9-4e16-81de-050fa0a4c343,emergency,assigned,8d975f8a-3c15-42d6-a033-74e9628c5264,2025-08-26 21:46:50,2025-08-31 11:50:08,2025-08-24 07:00:05,...,76,hours,Of rule hair purpose assume spend ahead.,0,NaN,2025-08-22 15:07:33,2026-04-05 08:43:54.365467,cc2555ee-e5c1-4669-aca1-83f864c40cc6,669ec047-53d7-49d1-a002-fe9351e4ec17,"[{""name"": ""Whitney Hernandez"", ""residency"": ""8..."
4,4adad1ae-f045-4757-85cc-7d87168743bd,405ede15-a7de-4016-ac93-ad7492d87992,Treat firm identify along seven whether future...,3e2c4423-8138-4232-8259-5c1d1e65625d,emergency,assigned,2420f3e7-c826-47ed-9895-1c516c602cfa,2025-06-13 16:24:14,2025-06-21 15:16:38,2025-06-11 19:20:45,...,5,hours,Word she investment.,1,Box again customer dinner decision.,2025-06-11 09:55:30,2026-04-05 08:43:54.368804,2d320378-187a-4ea9-9416-45799c49c675,fc38562b-f9e3-4bd7-9c70-858b6032c5bd,"[{""name"": ""Robert Holmes"", ""residency"": ""235 G..."

In [6]:
# tickets['quarter'] = tickets['created_at'].dt.quarter

In [7]:
# completed_tickets = tickets[tickets['status'] == 'completed']
# completed_tickets.shape

In [8]:
# completed_tickets['completion_time'] = completed_tickets['completed_at'] - completed_tickets['assigned_at']

In [9]:
# completed_tickets['response_time'] = completed_tickets['start_time'] - completed_tickets['assigned_at']

In [10]:
# completed_tickets.groupby('quarter')['completion_time'].mean()

In [11]:
# completed_tickets.groupby('quarter')['response_time'].mean()

In [12]:
# completed_tickets.groupby('quarter')['ticket_id'].count()

In [13]:
# tickets['month'] = tickets['created_at'].dt.month_name()

In [14]:
# tickets[tickets['quarter'] == 4].month.value_counts()

In [15]:
# completed_tickets.groupby('vendor_id')['completion_time'].mean().sort_values(ascending=False)

In [16]:
# completed_tickets.groupby('vendor_id')['response_time'].mean().sort_values(ascending=False)

In [17]:
# completed_tickets.groupby('vendor_id')['ticket_id'].count()

In [18]:
# vendor_kpis = completed_tickets.groupby('vendor_id').agg({
#     "completion_time": 'mean',
#     "response_time": 'mean',
#     "ticket_id": 'count'
# })
# vendor_kpis

In [19]:
# vendor_info = vendors[['vendor_id', 'company_name']]

In [20]:
# vendor_info

In [21]:
# pd.merge(vendor_info, vendor_kpis, on='vendor_id')

# Vendor/Client Admin KPIs

## On Time Delivery %
percentage of tickets completed on time within a specified range

In [22]:
cols = ['ticket_id', 'created_at', 'assigned_at', 'start_time', 'completed_at', 'due_date']

In [23]:
def overall_vendor_on_time_delivery(start_time, end_time=datetime.now()):
    df = tickets[tickets['created_at'].between(start_time, end_time)]
    completed_late = df['completed_at'] > df['due_date']
    overdue = (df['completed_at'].isna()) & (df['due_date'] < end_time)

    df['on_time'] = ~(completed_late | overdue)

    ticket_kpi = df.groupby('vendor_id').agg({
        'on_time': 'mean',
        'ticket_id': 'count'
    })
    ticket_kpi['on_time'] = (ticket_kpi['on_time'] * 100).round(2)
    vendor_info = vendors[['vendor_id', 'company_name']]

    vendor_kpi = pd.merge(vendor_info, ticket_kpi, on='vendor_id')
    return vendor_kpi

In [24]:
# three_months = pd.Timestamp.now() - pd.DateOffset(months=3)
# tickets_created_3_months = tickets[tickets['created_at'] >= three_months].reset_index()

# completed_late = tickets_created_3_months['completed_at'] > tickets_created_3_months['due_date']
# overdue = (tickets_created_3_months['completed_at'].isna()) & (tickets_created_3_months['due_date'] < pd.Timestamp.now())

# tickets_created_3_months['on_time'] = ~(completed_late | overdue)

# # tickets_created_3_months[cols].head(10)

# tickets_created_3_months['on_time'].value_counts(normalize=True)

# # tickets_created_3_months[tickets_created_3_months['on_time'] == True][cols]

# tickets_created_3_months.groupby('vendor_id')['on_time'].mean().round(4) * 100

In [25]:
nov_2025 = datetime.strptime('2025-11-01', '%Y-%m-%d')
feb_2026 = datetime.strptime('2026-03-01', '%Y-%m-%d')

In [26]:
overall_vendor_on_time_delivery(nov_2025, feb_2026)

,vendor_id,company_name,on_time,ticket_id
0,0ded7f06-ed67-4a95-a21d-2c431e38c883,Lee Inc,31.90,210
1,cee53164-4353-443b-87fe-d45aa142b0eb,Gardner Group,31.33,166
2,a64c8bad-2eed-4f71-9a2c-ab6446555b42,"Horn, Buchanan and Smith",29.60,125
3,cd464691-0ec1-4610-90bd-ddf7f41e4b75,"Hunter, Cardenas and Dalton",39.67,184
4,ca790bf9-a3d5-441e-9e35-13b30dd2f3a3,Fletcher-Gonzalez,36.43,140
5,1c9ccf14-5176-4c6c-8254-4abf7d027bfa,Williams-Owens,35.45,220
6,2420f3e7-c826-47ed-9895-1c516c602cfa,Walker-Kirby,41.67,144
7,084e231e-e1f9-43f1-9eea-8501ecc87efe,Mercer Inc,44.02,184
8,0cfc4b3e-0118-42f1-8bd8-617ccf8310cd,"Welch, Terry and Hood",39.47,114
9,8d975f8a-3c15-42d6-a033-74e9628c5264,Simmons Group,33.09,139

In [27]:
overall_vendor_on_time_delivery(nov_2025)

,vendor_id,company_name,on_time,ticket_id
0,0ded7f06-ed67-4a95-a21d-2c431e38c883,Lee Inc,31.34,284
1,cee53164-4353-443b-87fe-d45aa142b0eb,Gardner Group,34.68,222
2,a64c8bad-2eed-4f71-9a2c-ab6446555b42,"Horn, Buchanan and Smith",27.38,168
3,cd464691-0ec1-4610-90bd-ddf7f41e4b75,"Hunter, Cardenas and Dalton",38.56,236
4,ca790bf9-a3d5-441e-9e35-13b30dd2f3a3,Fletcher-Gonzalez,37.36,174
5,1c9ccf14-5176-4c6c-8254-4abf7d027bfa,Williams-Owens,35.52,290
6,2420f3e7-c826-47ed-9895-1c516c602cfa,Walker-Kirby,41.97,193
7,084e231e-e1f9-43f1-9eea-8501ecc87efe,Mercer Inc,38.89,234
8,0cfc4b3e-0118-42f1-8bd8-617ccf8310cd,"Welch, Terry and Hood",36.00,150
9,8d975f8a-3c15-42d6-a033-74e9628c5264,Simmons Group,37.04,189

In [28]:
(tickets['completed_at'].dt.normalize() == datetime.today().date()).sum()

np.int64(0)

In [29]:
tickets['completed_at'].dt.normalize().value_counts()

completed_at
2025-06-06    12
2026-03-31    12
2025-11-21    12
2026-01-28    11
2025-07-08    10
              ..
2025-10-24     1
2026-03-14     1
2025-12-17     1
2026-01-12     1
2025-08-14     1
Name: count, Length: 365, dtype: int64

## Average Duration of Ticket

In [30]:
df = tickets[~tickets['completed_at'].isna()]
df.shape

(1645, 25)

In [31]:
df['completion_time'] = df['completed_at'] - df['assigned_at']

In [32]:
df['completion_time'].mean()

Timedelta('1 days 17:57:54.276595')

In [33]:
def overall_vendor_ticket_duration(start_time, end_time=datetime.now()):
    df = tickets[tickets['completed_at'].between(start_time, end_time)] # all completed tickets in time range
    df['completion_time'] = df['completed_at'] - df['assigned_at']

    kpi = df.groupby('vendor_id')['completion_time'].mean().sort_values(ascending=True)
    vendor_info = vendors[['vendor_id', 'company_name']]

    vendor_kpi = pd.merge(vendor_info, kpi, on='vendor_id')

    return vendor_kpi

In [34]:
overall_vendor_ticket_duration(nov_2025, feb_2026)

,vendor_id,company_name,completion_time
0,0ded7f06-ed67-4a95-a21d-2c431e38c883,Lee Inc,1 days 22:35:02.362068
1,cee53164-4353-443b-87fe-d45aa142b0eb,Gardner Group,1 days 21:03:46.826086
2,a64c8bad-2eed-4f71-9a2c-ab6446555b42,"Horn, Buchanan and Smith",1 days 15:26:37.969696
3,cd464691-0ec1-4610-90bd-ddf7f41e4b75,"Hunter, Cardenas and Dalton",1 days 14:47:17.156250
4,ca790bf9-a3d5-441e-9e35-13b30dd2f3a3,Fletcher-Gonzalez,1 days 13:38:55.422222
5,1c9ccf14-5176-4c6c-8254-4abf7d027bfa,Williams-Owens,1 days 21:07:39.617647
6,2420f3e7-c826-47ed-9895-1c516c602cfa,Walker-Kirby,1 days 16:34:39.705882
7,084e231e-e1f9-43f1-9eea-8501ecc87efe,Mercer Inc,1 days 18:27:21.571428
8,0cfc4b3e-0118-42f1-8bd8-617ccf8310cd,"Welch, Terry and Hood",1 days 21:32:14.230769
9,8d975f8a-3c15-42d6-a033-74e9628c5264,Simmons Group,1 days 15:23:36.866666

In [35]:
overall_vendor_ticket_duration(nov_2025)

,vendor_id,company_name,completion_time
0,0ded7f06-ed67-4a95-a21d-2c431e38c883,Lee Inc,1 days 19:50:59.948717
1,cee53164-4353-443b-87fe-d45aa142b0eb,Gardner Group,1 days 18:01:30.859375
2,a64c8bad-2eed-4f71-9a2c-ab6446555b42,"Horn, Buchanan and Smith",1 days 15:25:21.800000
3,cd464691-0ec1-4610-90bd-ddf7f41e4b75,"Hunter, Cardenas and Dalton",1 days 15:49:54.362500
4,ca790bf9-a3d5-441e-9e35-13b30dd2f3a3,Fletcher-Gonzalez,1 days 16:23:52.283333
5,1c9ccf14-5176-4c6c-8254-4abf7d027bfa,Williams-Owens,1 days 18:30:52.670329
6,2420f3e7-c826-47ed-9895-1c516c602cfa,Walker-Kirby,1 days 16:17:57.300000
7,084e231e-e1f9-43f1-9eea-8501ecc87efe,Mercer Inc,1 days 19:37:20.586206
8,0cfc4b3e-0118-42f1-8bd8-617ccf8310cd,"Welch, Terry and Hood",2 days 00:00:56.215686
9,8d975f8a-3c15-42d6-a033-74e9628c5264,Simmons Group,1 days 13:57:34.539682

## Currently Open Tickets

In [36]:
def overall_vendor_open_tickets():
    open_tickets = tickets[tickets['status'] != 'completed']
    kpi = pd.pivot_table(open_tickets, index='vendor_id', columns='status', values='ticket_id', aggfunc='count').reset_index()
    kpi['total'] = kpi['assigned'] + kpi['in progress']
    vendor_info = vendors[['vendor_id', 'company_name']]

    vendor_kpi = pd.merge(vendor_info, kpi, on='vendor_id')
    return vendor_kpi

In [37]:
overall_vendor_open_tickets()

,vendor_id,company_name,assigned,in progress,total
0,0ded7f06-ed67-4a95-a21d-2c431e38c883,Lee Inc,216,228,444
1,cee53164-4353-443b-87fe-d45aa142b0eb,Gardner Group,186,162,348
2,a64c8bad-2eed-4f71-9a2c-ab6446555b42,"Horn, Buchanan and Smith",150,140,290
3,cd464691-0ec1-4610-90bd-ddf7f41e4b75,"Hunter, Cardenas and Dalton",187,180,367
4,ca790bf9-a3d5-441e-9e35-13b30dd2f3a3,Fletcher-Gonzalez,112,157,269
5,1c9ccf14-5176-4c6c-8254-4abf7d027bfa,Williams-Owens,239,228,467
6,2420f3e7-c826-47ed-9895-1c516c602cfa,Walker-Kirby,131,147,278
7,084e231e-e1f9-43f1-9eea-8501ecc87efe,Mercer Inc,170,177,347
8,0cfc4b3e-0118-42f1-8bd8-617ccf8310cd,"Welch, Terry and Hood",107,114,221
9,8d975f8a-3c15-42d6-a033-74e9628c5264,Simmons Group,160,164,324