In [1]:
import pandas as pd
import sqlite3
from datetime import datetime, timedelta

In [2]:
conn = sqlite3.connect("./my_database.db")

In [3]:
addresses = pd.read_sql_query(
    "select * from address", conn,
    parse_dates=['created_at', 'updated_at']
)

In [4]:
contractors = pd.read_sql_query(
    "select * from contractors", conn,
    parse_dates=['created_at', 'updated_at']
)

In [5]:
invoices = pd.read_sql_query(
    "select * from invoice", conn,
    parse_dates=['invoice_date', 'created_at', 'updated_at']
)

In [6]:
line_items = pd.read_sql_query(
    "select * from line_item", conn,
    parse_dates=['created_at', 'updated_at']
)

In [7]:
tickets = pd.read_sql_query(
    "select * from ticket", conn,
    parse_dates=['assigned_at', 'completed_at', 'created_at', 'updated_at', 'start_time', 'due_date']
)

In [8]:
users = pd.read_sql_query(
    "select * from user", conn,
    parse_dates=['created_at', 'updated_at']
)

In [9]:
vendor_users = pd.read_sql_query(
    "select * from vendor_user", conn,
    parse_dates=['created_at', 'updated_at']
)

In [10]:
vendor_wells = pd.read_sql_query(
    "select * from vendor_well", conn,
    parse_dates=['created_at', 'updated_at']
)

In [11]:
vendors = pd.read_sql_query(
    "select * from vendor", conn,
    parse_dates=['created_at', 'updated_at']
)

In [12]:
well_locations = pd.read_sql_query(
    "select * from well_location", conn,
    parse_dates=['created_at', 'updated_at']
)

In [13]:
wells = pd.read_sql_query(
    "select * from well", conn,
    parse_dates=['created_at', 'updated_at']
)

In [14]:
work_orders = pd.read_sql_query(
    "select * from work_orders", conn,
    parse_dates=['created_at', 'updated_at', 'estimated_start_date', 'estimated_end_date']
)

In [15]:
contractor_performance = pd.read_sql_query(
    "select * from contractor_performance", conn,
    parse_dates=['created_at', 'updated_at']
)

In [16]:
contractors.head()

,contractor_id,employee_number,vendor_id,vendor_manager_id,user_id,role,status,biometric_enrolled,is_onboarded,is_subcontractor,...,address_id,average_rating,years_experience,background_check_id,preferred_job_types,drug_test_id,created_at,updated_at,created_by,updated_by
0,5a492514-38a8-4ec3-8155-78c268a78784,EMP1219,b0f3789f-11b3-4e6d-8205-dcb3381ef2ba,cd1d59a0-89c8-4561-9338-22983d9333bb,4be33017-0d18-4bcf-964e-0f2edc0baa83,user,active,0,1,0,...,d270aa1e-1d6a-4ff7-8886-9dcf114069f8,1.19,17,652d8bbe-ed0e-469f-9c7f-661459eeac93,"[""Civil engineer, contracting"", ""Surveyor, min...",e039f19c-eb59-4a5a-932a-d0a41c57edbf,2026-01-15 21:42:28,2026-04-07 18:12:43.610769,41204b59-5163-49e7-9f0c-b908f5085baf,96f59913-e694-49bb-be6e-a84aa229184e
1,35c55da3-45ea-4457-94d9-d64479c01d16,EMP2079,1b193ccd-19a1-4d90-802b-c54dafe33648,a3432d97-1bff-4c9e-ae75-c514516cfe92,ac5e3a1f-1848-4fe0-8431-a5bb19c4154b,admin,inactive,1,1,0,...,c2cc05ec-1927-4b0f-94fa-f3852e31ddb6,2.22,0,f9567b03-89cd-45f3-8569-16e5d97617f3,"[""Chief Strategy Officer"", ""Scientist, researc...",ace063b3-07b7-4cbb-8ad8-5ebdd014a75d,2025-06-21 05:13:53,2026-04-07 18:12:43.610809,93d884ae-9dbb-4112-90fc-4a3515d52cf1,6a54399c-619b-40a4-8097-f14d87345075
2,2876f06d-5cfc-4a46-943f-4805f041c997,EMP6281,1183ff2b-4d45-4bb5-b674-7441c73903cc,cad4b599-f60f-4f89-9b88-a7b77bd899f6,719da42a-1bad-47ee-882b-31c1ff45ec7c,user,active,0,0,0,...,ab79a49d-31a3-44e6-be73-340199153628,3.95,21,8e13a617-6168-43ad-9449-82b6c763b578,"[""Scientist, clinical (histocompatibility and ...",252e9a38-40fd-49a4-bee1-45530bc20780,2026-01-23 01:59:28,2026-04-07 18:12:43.610841,59570b75-7b83-4437-82a3-671a3d1d8f4e,41b3f2b7-3300-4fc8-a404-a6cc1c33d44b
3,ab1c71e6-8332-4a8e-ab4e-b8c7db506baf,EMP4434,1b193ccd-19a1-4d90-802b-c54dafe33648,7482a920-6eb0-493e-9dde-5f957e316591,ebb5b7af-dde4-4632-b138-11804bd03af4,manager,inactive,0,1,0,...,5e62b351-aad6-44af-850e-46f4a73bfe74,3.71,9,5e3ae2b1-495e-4b1b-86f7-ec61b59b95d6,"[""Adult nurse"", ""Medical laboratory scientific...",01fdbe73-a4b8-4e23-ae0d-328002430d5d,2025-06-10 04:17:59,2026-04-07 18:12:43.610869,13f4c415-156a-41d1-9023-f569d319139a,290a7d1f-aaaf-4be1-a000-1a3f66210acd
4,b35ab78a-0905-4e7c-9e3d-adb6205bbdb7,EMP9114,1885aabf-2070-43a3-8f8d-71e67ae9409f,5c69eb90-c8ed-44bc-984b-8929f18fbae5,6ba13509-d030-4469-b035-10b885f50d52,admin,inactive,0,1,0,...,5c727993-a917-421c-b710-542629a0b12f,2.18,28,3a5f9578-800e-429e-978b-e8c74ff2aa97,"[""Therapist, nutritional"", ""Occupational thera...",9172a182-15b6-473b-b2b0-420220261b5f,2026-04-06 07:44:35,2026-04-07 18:12:43.610896,a48d2edd-687f-4c4a-9b2f-6dfd625be35a,8eeb19c1-6f6f-44c1-a4ad-42644420c364

## Vendor Manager KPIs

In [17]:
test_vendor = vendors.iloc[0]['vendor_id']
test_vendor

'1b193ccd-19a1-4d90-802b-c54dafe33648'

In [18]:
# def contractor_performance_kpi(vendor_id):
#     vendor_contractors = contractors[contractors['vendor_id'] == vendor_id]['contractor_id']
#     df = contractor_performance[contractor_performance['contractor_id'].isin(vendor_contractors)]
#     return df.groupby(['contractor_id'])['rating'].mean().sort_values(ascending=False)

In [19]:
# contractor_performance.head()

## Vendor Rating

In [20]:
def vendor_rating(vendor_id):
    vendor_contractors = contractors[contractors['vendor_id'] == vendor_id]['contractor_id']
    df = contractor_performance[contractor_performance['contractor_id'].isin(vendor_contractors)]
    return {'vendor_id': vendor_id, 'average_rating': df['rating'].mean().round(2)}

In [21]:
vendor_rating(test_vendor)

{'vendor_id': '1b193ccd-19a1-4d90-802b-c54dafe33648',
 'average_rating': np.float64(3.1)}

## Number of active contractors

In [22]:
def active_contractors(vendor_id):
    active_contractors = contractors[(contractors['vendor_id'] == vendor_id) & (contractors['status'] == 'active')]
    return {'vendor_id': vendor_id, 'active_contractors_num': active_contractors.shape[0]}

In [23]:
active_contractors(test_vendor)

{'vendor_id': '1b193ccd-19a1-4d90-802b-c54dafe33648',
 'active_contractors_num': 5}

## Jobs Completed This/Last Month (work in progress)

In [24]:
tickets.columns

Index(['ticket_id', 'work_order_id', 'description', 'assigned_contractor',
       'priority', 'status', 'vendor_id', 'start_time', 'due_date',
       'assigned_at', 'completed_at', 'estimated_duration', 'notes',
       'contractor_start_location', 'contractor_end_location',
       'estimated_quantity', 'unit', 'special_requirements', 'anomaly_flag',
       'anomaly_reason', 'created_at', 'updated_at', 'created_by',
       'updated_by', 'additional_information'],
      dtype='str')

In [25]:
def jobs_completed_current_month(vendor_id):
    now = pd.Timestamp.now()
    start_of_month = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0)

    completed_tickets_this_month = tickets[(tickets['vendor_id'] == vendor_id) & (tickets['status'] == 'completed') & (tickets['completed_at'] >= start_of_month)]
    return completed_tickets_this_month

In [26]:
jobs_completed_current_month(test_vendor)

Empty DataFrame
Columns: [ticket_id, work_order_id, description, assigned_contractor, priority, status, vendor_id, start_time, due_date, assigned_at, completed_at, estimated_duration, notes, contractor_start_location, contractor_end_location, estimated_quantity, unit, special_requirements, anomaly_flag, anomaly_reason, created_at, updated_at, created_by, updated_by, additional_information]
Index: []

[0 rows x 25 columns]

In [27]:
def jobs_completed_last_month(vendor_id):
    now = pd.Timestamp.now()
    start_of_last_month = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0) - pd.offsets.MonthBegin(1)

    completed_tickets_last_month = tickets[(tickets['vendor_id'] == vendor_id) & (tickets['status'] == 'completed') & (tickets['completed_at'] >= start_of_last_month)]
    return completed_tickets_last_month

In [28]:
jobs_completed_last_month(test_vendor)

,ticket_id,work_order_id,description,assigned_contractor,priority,status,vendor_id,start_time,due_date,assigned_at,...,estimated_quantity,unit,special_requirements,anomaly_flag,anomaly_reason,created_at,updated_at,created_by,updated_by,additional_information
2039,d85e3fdd-d835-42ce-851d-8629486ef035,88be345b-6a6d-465d-8981-c5cb5f400729,Man stay happen able member chance decide. Thi...,9421714d-2b13-4157-b2fd-eeaec85ee4d8,urgent,completed,1b193ccd-19a1-4d90-802b-c54dafe33648,2026-03-01 05:19:29,2026-03-06 22:59:40,2026-02-17 00:05:58,...,18,hours,Street whether theory next here material parti...,0,NaN,2026-02-15 20:07:40,2026-04-07 18:12:47.753189,8eeb19c1-6f6f-44c1-a4ad-42644420c364,73f2c6ae-8ba5-4c40-9c8f-26148f7fa8d6,"[{""name"": ""Charles Johnston"", ""residency"": ""37..."
4172,1aeb9e51-2519-4b94-a235-37072cbf048f,88be345b-6a6d-465d-8981-c5cb5f400729,Man stay happen able member chance decide. Thi...,ab1c71e6-8332-4a8e-ab4e-b8c7db506baf,urgent,completed,1b193ccd-19a1-4d90-802b-c54dafe33648,2026-02-26 22:14:07,2026-03-06 22:59:40,2026-02-25 23:30:24,...,3,hours,Necessary western with join simply personal.,0,NaN,2026-02-14 03:59:33,2026-04-07 18:12:52.017061,be5c577b-9c20-406d-adf9-c04534a87979,9569c4c8-12ba-4abe-8675-082d380dc22b,"[{""name"": ""Thomas Pratt"", ""residency"": ""870 Ke..."

## On Time Completion

In [29]:
# def contractor_on_time_delivery(vendor_id, start_time, end_time=datetime.now()):
#     start_time = pd.to_datetime(start_time)
#     end_time = pd.to_datetime(end_time)
#     df = tickets[(tickets['completed_at'].between(start_time, end_time)) & (tickets['vendor_id'] == vendor_id)]
#     completed_late = df['completed_at'] > df['due_date']
#     overdue = (df['completed_at'].isna()) & (df['due_date'] < end_time)
#     # print(df.head())
#     df['on_time'] = ~(completed_late | overdue)

#     ticket_kpi = df.groupby('assigned_contractor').agg({
#         'on_time': 'mean',
#         'ticket_id': 'count'
#     })
#     ticket_kpi.rename(columns={'ticket_id': 'ticket_count'}, inplace=True)
#     ticket_kpi['on_time'] = (ticket_kpi['on_time'] * 100).round(2)
#     contractor_info = contractors[contractors['contractor_id'].isin(df['assigned_contractor'])]

#     vendor_kpi = pd.merge(contractor_info, ticket_kpi, left_on='contractor_id', right_on='assigned_contractor').sort_values(by='on_time', ascending=False)
#     vendor_kpi = vendor_kpi[['employee_number', 'on_time', 'ticket_count']]
#     return vendor_kpi

In [30]:
def contractor_on_time_delivery(vendor_id, start_time, end_time=None):
    if end_time is None:
        end_time = datetime.now()

    start_time = pd.to_datetime(start_time)
    end_time = pd.to_datetime(end_time)

    df = tickets[
        (tickets["vendor_id"] == vendor_id) &
        (tickets["due_date"].between(start_time, end_time, inclusive="both"))
    ].copy()

    df["on_time"] = (
        df["completed_at"].notna() &
        (df["completed_at"] <= df["due_date"])
    )

    ticket_kpi = (
        df.groupby("assigned_contractor", as_index=False)
          .agg(
              on_time_count=("on_time", "sum"),
              ticket_count=("ticket_id", "count")
          )
    )

    ticket_kpi["on_time_pct"] = (
        ticket_kpi["on_time_count"] / ticket_kpi["ticket_count"] * 100
    ).round(2)

    contractor_info = contractors[
        contractors["contractor_id"].isin(ticket_kpi["assigned_contractor"])
    ][["contractor_id", "employee_number"]]

    return (
        contractor_info.merge(
            ticket_kpi,
            left_on="contractor_id",
            right_on="assigned_contractor",
            how="inner"
        )
        .sort_values(by="on_time_pct", ascending=False)
        [["employee_number", "on_time_count", "ticket_count", "on_time_pct"]]
    )

In [31]:
oct25 = datetime.strptime('2025-10-01', '%Y-%m-%d').date()
nov25 = datetime.strptime('2025-11-01', '%Y-%m-%d').date()
dec25 = datetime.strptime('2025-12-01', '%Y-%m-%d').date()

In [32]:
contractor_on_time_delivery(test_vendor, oct25, nov25)

   employee_number  on_time_count  ticket_count  on_time_pct
0          EMP2079              0             2          0.0
1          EMP4434              0             3          0.0
2          EMP4461              0             1          0.0
3          EMP1899              0             1          0.0
4          EMP2073              0             2          0.0
5          EMP8943              0             5          0.0
6          EMP8225              0             1          0.0
7          EMP9730              0             3          0.0
8          EMP3552              0             2          0.0
9          EMP2082              0             3          0.0
10         EMP7020              0             4          0.0
11         EMP2118              0             2          0.0

In [33]:
contractor_on_time_delivery(test_vendor, nov25, dec25)

   employee_number  on_time_count  ticket_count  on_time_pct
8          EMP3552              2             5        40.00
5          EMP8943              3            10        30.00
9          EMP2082              2             9        22.22
1          EMP4434              2            12        16.67
7          EMP9730              1             6        16.67
2          EMP4461              1             7        14.29
11         EMP2118              1             8        12.50
0          EMP2079              0             6         0.00
3          EMP1899              0             5         0.00
4          EMP2073              0             4         0.00
6          EMP8225              0             6         0.00
10         EMP7020              0             7         0.00

In [34]:
test_vendor

'1b193ccd-19a1-4d90-802b-c54dafe33648'

In [35]:
tickets.columns

Index(['ticket_id', 'work_order_id', 'description', 'assigned_contractor',
       'priority', 'status', 'vendor_id', 'start_time', 'due_date',
       'assigned_at', 'completed_at', 'estimated_duration', 'notes',
       'contractor_start_location', 'contractor_end_location',
       'estimated_quantity', 'unit', 'special_requirements', 'anomaly_flag',
       'anomaly_reason', 'created_at', 'updated_at', 'created_by',
       'updated_by', 'additional_information'],
      dtype='str')

## Overdue Tickets

In [36]:
overdue = tickets[(tickets['due_date'] < datetime.now()) & (tickets['status'] != 'completed') & (tickets['vendor_id'] == test_vendor)].copy()
overdue.shape

(873, 25)

In [37]:
tickets[['ticket_id', 'start_time', 'due_date', 'assigned_at', 'completed_at', 'assigned_contractor', 'status']].head()

,ticket_id,start_time,due_date,assigned_at,completed_at,assigned_contractor,status
0,759dcf2c-f7b7-4e70-8c5b-b1b90fc255f9,NaT,2024-11-29 11:28:17,2024-11-16 06:00:33,NaT,797e2635-6d52-4232-b961-590fa6151e66,assigned
1,949e45df-6735-4848-b832-8d68171dae05,NaT,2024-06-01 07:49:59,2024-05-01 19:47:28,NaT,27986bcc-79c9-4031-8de5-5c44819b054a,assigned
2,1c06c989-d30d-4893-95f2-ad4923e9e19e,2025-04-12 06:31:28,2025-04-19 01:35:03,2025-04-02 01:43:33,2025-04-15 09:47:37,c5da253b-eb9a-4b94-9114-7b0a09fb54c5,completed
3,45dcf846-0ae3-442d-a262-54979fed7e47,2024-07-17 03:33:13,2024-07-30 04:59:00,2024-07-16 22:20:01,2024-08-07 11:59:42,429c7536-fb65-4b4c-95ce-c0e74c69ddea,completed
4,8a77baad-ac16-499f-96f1-bb5495d6a593,NaT,2024-10-20 06:49:08,2024-09-25 16:46:29,NaT,2dfbdbbb-acd4-4d7b-814e-f29e637a95ee,assigned

In [38]:
# def overdue_tickets(vendor_id):
#     overdue = tickets[(tickets['due_date'] < datetime.now()) & (tickets['status'] != 'completed') & (tickets['vendor_id'] == vendor_id)].copy()
#     return overdue

In [39]:
# overdue_tickets(test_vendor)