In [ ]:
import pandas as pd
import sqlite3
from datetime import datetime, timedelta

In [ ]:
conn = sqlite3.connect("./my_database.db")

In [ ]:
addresses = pd.read_sql_query(
    "select * from address", conn,
    parse_dates=['created_at', 'updated_at']
)

In [ ]:
contractors = pd.read_sql_query(
    "select * from contractors", conn,
    parse_dates=['created_at', 'updated_at']
)

In [ ]:
invoices = pd.read_sql_query(
    "select * from invoice", conn,
    parse_dates=['invoice_date', 'created_at', 'updated_at']
)

In [ ]:
line_items = pd.read_sql_query(
    "select * from line_item", conn,
    parse_dates=['created_at', 'updated_at']
)

In [ ]:
tickets = pd.read_sql_query(
    "select * from ticket", conn,
    parse_dates=['assigned_at', 'completed_at', 'created_at', 'updated_at', 'start_time', 'due_date']
)

In [ ]:
tickets.columns

Index(['ticket_id', 'work_order_id', 'description', 'assigned_contractor',
       'priority', 'status', 'vendor_id', 'start_time', 'due_date',
       'assigned_at', 'completed_at', 'estimated_duration', 'notes',
       'contractor_start_location', 'contractor_end_location',
       'estimated_quantity', 'unit', 'special_requirements', 'anomaly_flag',
       'anomaly_reason', 'created_at', 'updated_at', 'created_by',
       'updated_by', 'additional_information'],
      dtype='str')

In [ ]:
users = pd.read_sql_query(
    "select * from user", conn,
    parse_dates=['created_at', 'updated_at']
)

In [ ]:
vendor_users = pd.read_sql_query(
    "select * from vendor_user", conn,
    parse_dates=['created_at', 'updated_at']
)

In [ ]:
vendor_wells = pd.read_sql_query(
    "select * from vendor_well", conn,
    parse_dates=['created_at', 'updated_at']
)

In [ ]:
vendors = pd.read_sql_query(
    "select * from vendor", conn,
    parse_dates=['created_at', 'updated_at']
)

In [ ]:
well_locations = pd.read_sql_query(
    "select * from well_location", conn,
    parse_dates=['created_at', 'updated_at']
)

In [ ]:
wells = pd.read_sql_query(
    "select * from well", conn,
    parse_dates=['created_at', 'updated_at']
)

In [ ]:
work_orders = pd.read_sql_query(
    "select * from work_orders", conn,
    parse_dates=['created_at', 'updated_at', 'estimated_start_date', 'estimated_end_date']
)

In [ ]:
contractor_performance = pd.read_sql_query(
    "select * from contractor_performance", conn,
    parse_dates=['created_at', 'updated_at']
)

In [ ]:
contractors.head()

,contractor_id,employee_number,vendor_id,vendor_manager_id,user_id,role,status,biometric_enrolled,is_onboarded,is_subcontractor,...,address_id,average_rating,years_experience,background_check_id,preferred_job_types,drug_test_id,created_at,updated_at,created_by,updated_by
0,1f35d659-d05c-45f9-a37e-463e0c0c0d50,EMP5675,911322fe-3a5a-473a-96dc-18edd47f2f4d,d5742de8-905c-428d-94bc-b1e6145d54bb,65d4cdca-9666-4200-8177-3278a1c06be9,admin,inactive,0,1,1,...,57817b9c-7648-46a3-b07d-fc25a2e2a97d,4.01,30,5bb732ba-0ca9-4197-a221-286394ec14be,"[""Logistics and distribution manager"", ""Artist""]",e880ac4a-f529-4ca4-b01c-15546eaf593e,2025-04-12 05:16:23,2026-04-08 08:15:26.543971,d91fa351-2ebe-432e-9a79-6eaf74f8dd8b,a62ca49d-bc8e-46d9-b020-7d925d46b6d1
1,486a5bd5-12f2-420d-be87-72e180a20d5f,EMP8815,911322fe-3a5a-473a-96dc-18edd47f2f4d,cb2ddd21-eb66-4e58-a775-2fed5bc41b80,7cdd29d8-7170-4918-8acd-badb55dd657e,user,inactive,0,0,0,...,07f54eba-732b-4237-ac34-5dfc45290f4f,1.62,11,f1dcb2b4-45cb-487b-9c64-25b231955b6a,"[""Chartered loss adjuster"", ""Conference centre...",cfdc9e4e-f6e9-4f3f-afb0-e1da0d1cf9fc,2025-06-03 08:30:03,2026-04-08 08:15:26.544015,86653d17-1126-478c-81eb-cc2c206b1efd,16159cc8-3736-427d-8fc6-5c84aa1f9c19
2,651ff3d5-4965-4610-8bbe-e1fec0a9d110,EMP9883,5d1adcb1-bfe4-4c89-9b6a-6871a4ac239b,fd32593f-5df5-4995-bef8-107495cd0911,57bdc776-db57-408d-8464-48fa2bfc1cdb,admin,inactive,0,1,0,...,43c3260a-3578-4a12-8c3d-e13c671466f0,1.55,6,bdcf3c69-06d9-41ae-9383-44517af6c399,"[""Financial controller"", ""Retail merchandiser""]",70122724-bfce-4d06-b78d-4b835ea1a384,2026-01-08 18:10:24,2026-04-08 08:15:26.544049,4c6e9381-1a98-455d-8bc3-3bb4c5b7b1ad,25bccc72-37c9-4fc1-bf48-aa2d9be2278e
3,74d51569-a3f5-40d5-b152-16937dfef154,EMP6090,c30eb1f0-bbeb-42c4-9bc5-7c4febd38838,93733cec-504f-46ab-9680-3f778011f3dd,9de045a4-2647-497f-8700-32aa94344a0e,user,active,0,0,0,...,4d99a6ef-c5ff-43cf-99a6-3be84e0a61bb,3.86,21,e9f86f84-42cb-4faf-8a2f-bc52ba8506a7,"[""Accommodation manager"", ""Chiropractor""]",49c9cf84-94ec-4115-a10b-1aff4d6e5da8,2025-05-06 23:52:39,2026-04-08 08:15:26.544079,d48f434b-88ec-4a9e-bd33-1c333a5e8a10,5c054362-242a-4b7f-b682-536391513f6b
4,a15bf638-bc10-4d09-b42d-bb4d722880e3,EMP7434,63cce387-ccdc-45da-b1b7-118fb636a479,98e10253-ab17-4530-8075-651432d8ddd8,4e1c2705-63b2-46d1-8df4-0af1adec83d8,manager,active,1,0,1,...,bc9433fb-17e4-4895-bd24-dfe9d15bf41f,3.65,24,2c1a460d-d3d1-4d91-91b8-4fb140c06968,"[""Psychologist, sport and exercise"", ""Engineer...",044071db-2fe4-405f-9594-85b6bb65e060,2025-08-17 15:05:39,2026-04-08 08:15:26.544108,f58db263-ffab-426f-a2d9-0d9adb4f23c4,d259794b-b34d-49f8-bd46-7f975e2b6a95

## Vendor Manager KPIs

In [ ]:
test_vendor = vendors.iloc[0]['vendor_id']
test_vendor

'911322fe-3a5a-473a-96dc-18edd47f2f4d'

In [ ]:
# def contractor_performance_kpi(vendor_id):
#     vendor_contractors = contractors[contractors['vendor_id'] == vendor_id]['contractor_id']
#     df = contractor_performance[contractor_performance['contractor_id'].isin(vendor_contractors)]
#     return df.groupby(['contractor_id'])['rating'].mean().sort_values(ascending=False)

In [ ]:
# contractor_performance.head()

## Vendor Rating

In [ ]:
def vendor_rating(vendor_id):
    vendor_contractors = contractors[contractors['vendor_id'] == vendor_id]['contractor_id']
    df = contractor_performance[contractor_performance['contractor_id'].isin(vendor_contractors)]
    return {'vendor_id': vendor_id, 'average_rating': df['rating'].mean().round(2)}

In [ ]:
vendor_rating(test_vendor)

{'vendor_id': '911322fe-3a5a-473a-96dc-18edd47f2f4d',
 'average_rating': np.float64(3.12)}

## Number of active contractors

In [ ]:
def active_contractors(vendor_id):
    active_contractors = contractors[(contractors['vendor_id'] == vendor_id) & (contractors['status'] == 'active')]
    return {'vendor_id': vendor_id, 'active_contractors_num': active_contractors.shape[0]}

In [ ]:
active_contractors(test_vendor)

{'vendor_id': '911322fe-3a5a-473a-96dc-18edd47f2f4d',
 'active_contractors_num': 6}

## Jobs Completed This/Last Month (work in progress)

In [ ]:
tickets.columns

Index(['ticket_id', 'work_order_id', 'description', 'assigned_contractor',
       'priority', 'status', 'vendor_id', 'start_time', 'due_date',
       'assigned_at', 'completed_at', 'estimated_duration', 'notes',
       'contractor_start_location', 'contractor_end_location',
       'estimated_quantity', 'unit', 'special_requirements', 'anomaly_flag',
       'anomaly_reason', 'created_at', 'updated_at', 'created_by',
       'updated_by', 'additional_information'],
      dtype='str')

In [ ]:
def jobs_completed_current_month(vendor_id):
    now = pd.Timestamp.now()
    start_of_month = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0)

    completed_tickets_this_month = tickets[(tickets['vendor_id'] == vendor_id) & (tickets['status'] == 'completed') & (tickets['completed_at'] >= start_of_month)]
    return completed_tickets_this_month

In [ ]:
jobs_completed_current_month(test_vendor)

Empty DataFrame
Columns: [ticket_id, work_order_id, description, assigned_contractor, priority, status, vendor_id, start_time, due_date, assigned_at, completed_at, estimated_duration, notes, contractor_start_location, contractor_end_location, estimated_quantity, unit, special_requirements, anomaly_flag, anomaly_reason, created_at, updated_at, created_by, updated_by, additional_information]
Index: []

[0 rows x 25 columns]

In [ ]:
def jobs_completed_last_month(vendor_id):
    now = pd.Timestamp.now()
    start_of_last_month = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0) - pd.offsets.MonthBegin(1)

    completed_tickets_last_month = tickets[(tickets['vendor_id'] == vendor_id) & (tickets['status'] == 'completed') & (tickets['completed_at'] >= start_of_last_month)]
    return completed_tickets_last_month

In [ ]:
jobs_completed_last_month(test_vendor)

,ticket_id,work_order_id,description,assigned_contractor,priority,status,vendor_id,start_time,due_date,assigned_at,...,estimated_quantity,unit,special_requirements,anomaly_flag,anomaly_reason,created_at,updated_at,created_by,updated_by,additional_information
40,00587713-0969-40c5-87b5-558a4f1403ce,37d7877e-6222-47f3-8465-c77049c35569,From really Democrat trip man task benefit. Tr...,1f35d659-d05c-45f9-a37e-463e0c0c0d50,urgent,completed,911322fe-3a5a-473a-96dc-18edd47f2f4d,2026-02-19 02:46:52,2026-03-01 21:33:40,2026-02-15 08:04:08,...,29,hours,Culture matter value receive agree front.,1,Science audience best.,2026-02-12 16:53:29,2026-04-08 08:15:26.851939,2b0c1242-cd65-4fe4-bbec-28b8c5964ec8,5f6f7697-489a-4edf-9796-1f0cdf64aeda,"[{""name"": ""Kristen Lewis"", ""residency"": ""923 E..."
1500,96c6aa63-c940-41d2-a45d-d1ad91556569,37d7877e-6222-47f3-8465-c77049c35569,From really Democrat trip man task benefit. Tr...,4a52f701-c85a-4ee6-8437-de6d6c73bcf3,urgent,completed,911322fe-3a5a-473a-96dc-18edd47f2f4d,2026-02-18 23:53:38,2026-03-01 21:33:40,2026-02-18 09:58:18,...,42,hours,Threat TV bill foreign democratic.,1,At green top dinner us and.,2026-02-07 06:42:04,2026-04-08 08:15:29.886539,2f690699-7979-49b9-afc3-9499d0cd9e78,46be4622-ad44-4ce8-a3b8-26089fdbf0f6,"[{""name"": ""Robert Schmidt"", ""residency"": ""329 ..."
2064,4e6e9087-88c7-4ac7-8d89-97539d1068db,37d7877e-6222-47f3-8465-c77049c35569,From really Democrat trip man task benefit. Tr...,b6be9d6b-79ba-4551-9856-af744a974102,urgent,completed,911322fe-3a5a-473a-96dc-18edd47f2f4d,2026-02-18 20:36:33,2026-03-01 21:33:40,2026-02-17 20:47:56,...,86,hours,Ball company finish direction.,0,NaN,2026-02-08 07:36:25,2026-04-08 08:15:31.046558,faee2b21-e1ef-40b9-a0fd-6b78e138558e,45133835-87ff-4cf9-b64c-c77618a2251a,"[{""name"": ""Margaret Edwards"", ""residency"": ""US..."
2088,60131a35-de65-4af3-8c59-c79f78f98efe,d7c1bc76-7579-4764-bb65-793a235e6b0a,Manage few within coach shoulder. Table beat c...,edd43bba-8651-4e37-ad36-de319bef623a,urgent,completed,911322fe-3a5a-473a-96dc-18edd47f2f4d,2026-01-23 11:22:20,2026-02-07 16:20:26,2026-01-23 10:29:16,...,80,hours,Those building risk.,0,According throw prepare.,2026-01-12 13:06:26,2026-04-08 08:15:31.096532,a3cbe8c6-66e9-4140-96e5-83c82bb72e40,23f82a04-4e05-420e-bc9d-f1109685aec5,"[{""name"": ""Steven Williams"", ""residency"": ""687..."
2501,4bd97a64-a9c8-4a54-96ec-405dd09a6f1a,37d7877e-6222-47f3-8465-c77049c35569,From really Democrat trip man task benefit. Tr...,be7682c9-c065-4ab4-b1d5-ae4084e36078,urgent,completed,911322fe-3a5a-473a-96dc-18edd47f2f4d,2026-02-18 18:52:00,2026-03-01 21:33:40,2026-02-17 12:07:34,...,34,hours,Else candidate situation push speak.,1,NaN,2026-02-06 17:35:25,2026-04-08 08:15:31.948530,f58db263-ffab-426f-a2d9-0d9adb4f23c4,4a8e0d89-14a8-4e0b-a6c3-b34cda59feec,"[{""name"": ""Mr. Timothy Valdez"", ""residency"": ""..."
2756,6fc2f6e8-6358-4d05-8fc2-25d667f74368,37d7877e-6222-47f3-8465-c77049c35569,From really Democrat trip man task benefit. Tr...,cea4f4be-a0af-44a9-91e3-e65f9becb6c6,urgent,completed,911322fe-3a5a-473a-96dc-18edd47f2f4d,2026-02-19 18:25:24,2026-03-01 21:33:40,2026-02-19 16:04:24,...,6,hours,Fast letter product edge.,1,NaN,2026-02-18 12:04:14,2026-04-08 08:15:32.458861,23f82a04-4e05-420e-bc9d-f1109685aec5,06fa2ac0-b6f1-4e6a-9eba-e7603da2a54c,"[{""name"": ""Rhonda Scott"", ""residency"": ""7097 W..."

## On Time Completion

In [ ]:
# def contractor_on_time_delivery(vendor_id, start_time, end_time=datetime.now()):
#     start_time = pd.to_datetime(start_time)
#     end_time = pd.to_datetime(end_time)
#     df = tickets[(tickets['completed_at'].between(start_time, end_time)) & (tickets['vendor_id'] == vendor_id)]
#     completed_late = df['completed_at'] > df['due_date']
#     overdue = (df['completed_at'].isna()) & (df['due_date'] < end_time)
#     # print(df.head())
#     df['on_time'] = ~(completed_late | overdue)

#     ticket_kpi = df.groupby('assigned_contractor').agg({
#         'on_time': 'mean',
#         'ticket_id': 'count'
#     })
#     ticket_kpi.rename(columns={'ticket_id': 'ticket_count'}, inplace=True)
#     ticket_kpi['on_time'] = (ticket_kpi['on_time'] * 100).round(2)
#     contractor_info = contractors[contractors['contractor_id'].isin(df['assigned_contractor'])]

#     vendor_kpi = pd.merge(contractor_info, ticket_kpi, left_on='contractor_id', right_on='assigned_contractor').sort_values(by='on_time', ascending=False)
#     vendor_kpi = vendor_kpi[['employee_number', 'on_time', 'ticket_count']]
#     return vendor_kpi

In [ ]:
def contractor_on_time_delivery(vendor_id, start_time, end_time=None):
    if end_time is None:
        end_time = datetime.now()

    start_time = pd.to_datetime(start_time)
    end_time = pd.to_datetime(end_time)

    df = tickets[
        (tickets["vendor_id"] == vendor_id) &
        (tickets["due_date"].between(start_time, end_time, inclusive="both"))
    ].copy()

    df["on_time"] = (
        df["completed_at"].notna() &
        (df["completed_at"] <= df["due_date"])
    )

    ticket_kpi = (
        df.groupby("assigned_contractor", as_index=False)
          .agg(
              on_time_count=("on_time", "sum"),
              ticket_count=("ticket_id", "count")
          )
    )

    ticket_kpi["on_time_pct"] = (
        ticket_kpi["on_time_count"] / ticket_kpi["ticket_count"] * 100
    ).round(2)

    contractor_info = contractors[
        contractors["contractor_id"].isin(ticket_kpi["assigned_contractor"])
    ][["contractor_id", "employee_number"]]

    return (
        contractor_info.merge(
            ticket_kpi,
            left_on="contractor_id",
            right_on="assigned_contractor",
            how="inner"
        )
        .sort_values(by="on_time_pct", ascending=False)
        [["employee_number", "on_time_count", "ticket_count", "on_time_pct"]]
    )

In [ ]:
oct25 = datetime.strptime('2025-10-01', '%Y-%m-%d').date()
nov25 = datetime.strptime('2025-11-01', '%Y-%m-%d').date()
dec25 = datetime.strptime('2025-12-01', '%Y-%m-%d').date()

In [ ]:
contractor_on_time_delivery(test_vendor, oct25, nov25)

  employee_number  on_time_count  ticket_count  on_time_pct
1         EMP7123              1             2         50.0
0         EMP8815              0             3          0.0
2         EMP0213              0             2          0.0
3         EMP8791              0             1          0.0
4         EMP3829              0             6          0.0
5         EMP9469              0             3          0.0
6         EMP8713              0             6          0.0
7         EMP3892              0             1          0.0

In [ ]:
contractor_on_time_delivery(test_vendor, nov25, dec25)

   employee_number  on_time_count  ticket_count  on_time_pct
4          EMP8791              3             7        42.86
3          EMP0213              2             7        28.57
6          EMP3829              2             7        28.57
9          EMP5218              1             8        12.50
2          EMP7123              0             3         0.00
0          EMP5675              0             1         0.00
1          EMP8815              0             1         0.00
5          EMP6305              0             2         0.00
7          EMP9469              0             1         0.00
8          EMP8713              0             4         0.00
10         EMP3892              0             4         0.00

In [ ]:
test_vendor

'911322fe-3a5a-473a-96dc-18edd47f2f4d'

In [ ]:
tickets.columns

Index(['ticket_id', 'work_order_id', 'description', 'assigned_contractor',
       'priority', 'status', 'vendor_id', 'start_time', 'due_date',
       'assigned_at', 'completed_at', 'estimated_duration', 'notes',
       'contractor_start_location', 'contractor_end_location',
       'estimated_quantity', 'unit', 'special_requirements', 'anomaly_flag',
       'anomaly_reason', 'created_at', 'updated_at', 'created_by',
       'updated_by', 'additional_information'],
      dtype='str')

## Overdue Tickets

In [ ]:
overdue = tickets[(tickets['due_date'] < datetime.now()) & (tickets['status'] != 'completed') & (tickets['vendor_id'] == test_vendor)].copy()
overdue.shape

(504, 25)

In [ ]:
overdue.head()

,ticket_id,work_order_id,description,assigned_contractor,priority,status,vendor_id,start_time,due_date,assigned_at,...,estimated_quantity,unit,special_requirements,anomaly_flag,anomaly_reason,created_at,updated_at,created_by,updated_by,additional_information
3,486676a8-0eec-45f9-bd0f-caeb70a01e82,c28c4b02-b9d5-4fa0-95c2-8cd81c955a66,Person politics particular realize surface. So...,4a52f701-c85a-4ee6-8437-de6d6c73bcf3,urgent,assigned,911322fe-3a5a-473a-96dc-18edd47f2f4d,NaT,2025-01-14 22:39:17,2024-12-26 07:15:07,...,14,hours,Push police line soldier material growth incre...,0,Home worry run site evidence language.,2024-12-22 22:47:27,2026-04-08 08:15:26.771058,64391410-c9ed-4642-b6db-d2c6ce77a996,72449740-6543-4b17-b768-07025ff60229,"[{""name"": ""Rodney Chen"", ""residency"": ""804 How..."
9,994cdd3b-3043-4a13-ae74-87bca478166e,b71830d7-fd03-4ee5-9582-ed834c807bed,Particular candidate mission support successfu...,f971a8f4-a046-4f59-8b6e-02a18b342e14,routine,assigned,911322fe-3a5a-473a-96dc-18edd47f2f4d,NaT,2025-08-06 10:33:14,2025-07-29 05:36:52,...,98,hours,Summer rather piece remember lot face father.,0,Friend miss gun financial recognize me brother...,2025-07-26 07:30:43,2026-04-08 08:15:26.783714,86420ff1-83bf-413a-90ef-d42173f05e0c,6abe0983-0401-4670-a87d-87439734230e,"[{""name"": ""Steve Rivera"", ""residency"": ""851 Ke..."
23,84d3ef45-7df6-412a-b673-de87ce86e4c6,dad9997b-a6cc-4968-b084-45c9bb237eb0,Find watch treatment with shoulder no fish par...,b6be9d6b-79ba-4551-9856-af744a974102,routine,assigned,911322fe-3a5a-473a-96dc-18edd47f2f4d,NaT,2025-01-06 01:26:17,2024-12-24 19:49:18,...,57,hours,Firm add north many anything.,0,NaN,2024-12-18 02:49:12,2026-04-08 08:15:26.814509,ba788ecc-fa44-480b-adac-5fe71f781e4a,e025f0d8-f624-4257-9ab4-4acb61d545aa,"[{""name"": ""Denise Todd"", ""residency"": ""773 Ken..."
38,cacefe64-4df1-4990-add5-a22ceb13673b,9a0c1732-6dc1-4fba-beb7-5bb66f674c90,Field hair box share against sense.\nHistory w...,1f35d659-d05c-45f9-a37e-463e0c0c0d50,routine,assigned,911322fe-3a5a-473a-96dc-18edd47f2f4d,NaT,2025-03-11 06:02:26,2025-02-13 06:11:08,...,28,hours,Suggest allow hard.,0,NaN,2025-01-31 04:46:58,2026-04-08 08:15:26.847796,3a8e0d0d-1e29-48b5-a792-d03838aa4567,3a8e0d0d-1e29-48b5-a792-d03838aa4567,"[{""name"": ""Jennifer Andrews"", ""residency"": ""67..."
47,b553088c-80ee-4258-8b31-16050a09373d,5289ef34-a545-420d-be40-6159bbe2b301,Image after instead raise administration. Laug...,486a5bd5-12f2-420d-be87-72e180a20d5f,emergency,assigned,911322fe-3a5a-473a-96dc-18edd47f2f4d,NaT,2025-01-21 06:43:00,2024-12-24 20:48:26,...,30,hours,Foot effort body its the.,1,National military way analysis detail.,2024-12-20 07:14:18,2026-04-08 08:15:26.866453,56fdd441-d2ff-4285-8b44-c834e8a740e3,e7c44e18-cfd0-4646-9b0c-8d0917a5b5b5,"[{""name"": ""Debra Barnes"", ""residency"": ""78003 ..."

In [ ]:
tickets[['ticket_id', 'start_time', 'due_date', 'assigned_at', 'completed_at', 'assigned_contractor', 'status']].head()

,ticket_id,start_time,due_date,assigned_at,completed_at,assigned_contractor,status
0,0f2f329e-a3b2-4d72-896e-4ea93ec9dd10,2025-11-22 06:03:59,2025-12-03 16:22:42,2025-11-17 08:03:37,NaT,79bccf17-8609-4f0e-9ce2-0e9fa05ac360,in progress
1,e5a61296-1d62-40af-a799-bfbdbd46e9bb,NaT,2026-03-15 11:01:59,2026-02-04 01:38:13,NaT,50419888-04cd-4645-bcdb-af3116d19da3,assigned
2,4e7920e6-c695-4e0d-b39d-901a970237b8,2024-10-19 21:35:20,2024-11-12 19:36:51,2024-10-11 18:13:59,2024-11-18 16:59:18,716554b2-14e9-4b84-81a1-017a1c1c3488,completed
3,486676a8-0eec-45f9-bd0f-caeb70a01e82,NaT,2025-01-14 22:39:17,2024-12-26 07:15:07,NaT,4a52f701-c85a-4ee6-8437-de6d6c73bcf3,assigned
4,e60a1b7e-b14a-46c7-b057-2bd4bf45c091,NaT,2025-02-12 02:31:01,2025-02-01 22:33:35,NaT,f7b7593b-51f7-4449-94d1-dad2937b6cea,assigned

In [ ]:
# def overdue_tickets(vendor_id):
#     overdue = tickets[(tickets['due_date'] < datetime.now()) & (tickets['status'] != 'completed') & (tickets['vendor_id'] == vendor_id)].copy()
#     return overdue

In [ ]:
# overdue_tickets(test_vendor)